<%   
   // aqui podria ir cualquier código java valido....
   // Incluso conexiones a base de datos para generar código HTML más dinámico...
     
   // Recibimos el parametro enviado por el formulario HTML...
   String name=request.getParameter("uname");  
   out.print("<h2><font color='blue'>Buenos dias "+ name + "</font></h2");  
%> 